/**
 * Whylee - Serve latest questions CSV
 * -----------------------------------
 * Delivers the newest daily questions file, generated by generate-questions.js.
 */

import fs from "fs";
import path from "path";

export const handler = async () => {
  try {
    const filePath = path.join(process.cwd(), "public", "questions.csv");

    if (!fs.existsSync(filePath)) {
      return { statusCode: 404, body: "No questions.csv file found yet." };
    }

    const data = fs.readFileSync(filePath, "utf8");

    return {
      statusCode: 200,
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Cache-Control": "no-cache, no-store, must-revalidate",
      },
      body: data,
    };
  } catch (error) {
    console.error("Error reading questions file:", error);
    return { statusCode: 500, body: "Error loading questions." };
  }
};
